### PR TITLE
feature/AQI-4631 added field Version,TenantId to protobuf type Report…

### PR DESCRIPTION
**Pull request by AlanLiu-AI**
…Definition.

### CODE REVIEW

**Comment by AlanLiu-AI** [comment]
This change linked with crucible review:
https://crucible.waterqualitytools.com/cru/CR-FF-9263

**Review by tomsmith-ai — APPROVED** [review]
thank Alan.

**Review by KentMiller — APPROVED** [review]

**Comment by AlanLiu-AI** [comment]
Close PR and deploy changes to feature for testing.

**Comment by AlanLiu-AI** [comment]
Test complete, reopen this PR for merge.

**Review by JonathanRobertson-AQI — APPROVED** [review]

**Pull request merged**
